version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "05:17"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 1
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "05:37"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 1
    groups:
      github-actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: ci
